# Generated by Django 2.2.11 on 2020-04-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='firstname',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='lastname',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
